//! Generates the list of autonomous algorithms (see `src/autonomous_control.rs`)
//! from whatever `.rs` files `src/autonomous_control/` holds, so adding an
//! algorithm is only a matter of adding its file - nothing else has to name
//! it.
//!
//! Writes `$OUT_DIR/autonomous_algorithms.rs`: one `mod` per file, and an
//! `all()` building one executor per file, named after its file stem.

use std::fmt::Write as _;
use std::path::Path;
use std::{env, fs};

const ALGORITHMS_DIR: &str = "src/autonomous_control";

fn main() {
    // A directory makes Cargo rescan everything under it, so adding,
    // removing, or editing an algorithm file all rerun this script.
    println!("cargo:rerun-if-changed={ALGORITHMS_DIR}");

    let manifest_dir =
        env::var("CARGO_MANIFEST_DIR").expect("cargo always sets CARGO_MANIFEST_DIR");
    let dir = Path::new(&manifest_dir).join(ALGORITHMS_DIR);

    let mut algorithms: Vec<(String, String)> = fs::read_dir(&dir)
        .map(|entries| {
            entries
                .filter_map(|entry| entry.ok().map(|entry| entry.path()))
                .filter(|path| path.is_file() && path.extension().is_some_and(|ext| ext == "rs"))
                .map(|path| {
                    let stem = path.file_stem().unwrap().to_string_lossy().into_owned();
                    assert!(
                        !stem.is_empty()
                            && stem.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
                            && !stem.starts_with(|c: char| c.is_ascii_digit()),
                        "{ALGORITHMS_DIR}/{stem}.rs: an algorithm's file name must be a snake_case Rust identifier"
                    );
                    (stem, path.to_string_lossy().into_owned())
                })
                .collect()
        })
        .unwrap_or_default();
    algorithms.sort();

    let mut out = String::from(
        "// @generated by build.rs from the files in src/autonomous_control/ - do not edit.\n\n",
    );
    for (stem, path) in &algorithms {
        // An absolute `#[path]`: a plain `mod` inside an `include!`d file
        // would be looked up relative to OUT_DIR, not to this module.
        writeln!(out, "#[path = {path:?}]\nmod {stem};").unwrap();
    }
    out.push_str(
        "\n/// One fresh executor per algorithm file in `src/autonomous_control/`, each\n\
         /// named after its file stem - see the [module docs](self).\n\
         pub fn all() -> Vec<Box<dyn crate::Executor>> {\n    vec![\n",
    );
    for (stem, _) in &algorithms {
        writeln!(out, "        {stem}::new({stem:?}),").unwrap();
    }
    out.push_str("    ]\n}\n");

    let out_path = Path::new(&env::var("OUT_DIR").expect("cargo always sets OUT_DIR"))
        .join("autonomous_algorithms.rs");
    fs::write(out_path, out).expect("failed to write the generated autonomous algorithm list");
}
